[package]
name = "aline"
version = "0.1.0"
authors = ["Brandon Holt <b.holt@apple.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
regex = "1.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1"

[dev-dependencies]
shlex = "0.1"