[package]
name = "aline"
version = "0.1.0"
authors = ["Brandon Holt <b.holt@apple.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1"
strfmt = "0"

[dev-dependencies]
shlex = "0.1"